version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend-service
    restart: always
    ports:
      - "5001:5000" # Expose backend on host port 5001
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: frontend-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    restart: always
    ports:
      - "4000:3000" # Expose Grafana on host port 4000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
