global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend-service"
    static_configs:
      - targets: ["backend:5000"] # Docker Compose service name

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
